with Bike_trip as (
select 
ride_id,
RIDE_TYPE,
DATE(TRY_TO_TIMESTAMP(STARTED_AT))as TRIP_DATE,
START_STATION_ID,
END_STATION_ID,
TIMESTAMPDIFF(SECOND,TRY_TO_TIMESTAMP(STARTED_AT),TRY_TO_TIMESTAMP(ENDED_AT)) as TRIP_DURATION_MINUTES,
MEMBER_CASUAL

from {{ source('demo', 'BIKES') }}
)
SELECT * FROM Bike_trip